# -*- coding: utf-8 -*-
{
    'name' : 'TRF',
    'version' : '1.0',
    'summary': 'TRF',
    'sequence': -100,
    'description': """TRF""",
    'category': 'Testing',
    'website': 'https://www.bonzapro.com',
    'depends': ['crm', 'mail', 'sale'],
    'data': [
        'security/ir.models.access.csv',
        'security/sales_group.xml',
        'security/trf_group.xml',
        'data/my_module_data.xml',
        'view/trf_form_view.xml',
        'view/trf_inherit_view.xml',
        'view/scope_matrix_view.xml',
        'view/sale_order_inherite.xml',
        'view/sale.xml',
        'report/report.xml',
        'report/trf_pdf_report.xml',
        'report/scope_matrix_pdf_report.xml',
        'report/proposal_pdf_report.xml',
    ],
    'demo': [],
    'qweb': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}
