# -*- coding: utf-8 -*-
{
    'name' : 'TRF',
    'version' : '1.0',
    'summary': 'TRF',
    'sequence': -100,
    'description': """TRF""",
    'category': 'Testing',
    'website': 'https://www.bonzapro.com',
    'depends': ['crm', 'mail', 'sale','project','maintenance', 'sale_crm'],
    'data': [
        'security/ir.model.access.csv',
        'security/sales_group.xml',
        'security/trf_group.xml',
        'data/data.xml',
        'view/trf_form_view.xml',
        'view/trf_inherit_view.xml',
        'view/scope_matrix_view.xml',
        #'view/sale_order_inherite.xml',
        'view/sale.xml',
        # 'view/protocol.xml',
        'view/protocol_task.xml',
        'view/crm_lead.xml',
        'report/report.xml',
        'report/trf_pdf_report.xml',
        'report/scope_matrix_pdf_report.xml',
        'report/proposal_pdf_report.xml',
        'report/protocol_layout.xml',
        'report/project_layout.xml',
        'report/test_report_layout.xml',
    ],
    'demo': [],
    'qweb': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}
