# -*- coding: utf-8 -*-
{
    'name' : 'Mitsui',
    'version' : '1.0',
    'summary': 'TRF',
    'sequence': -100,
    'description': """TRF""",
    'category': 'Testing',
    'website': 'https://www.bonzapro.com',
    'depends': ['project', 'bz_crm_trf','project_tasks_from_templates', 'account'],
    'data': [
        'security/ir.model.access.csv',
        'data/cron.xml',
        'data/mail_template.xml',
        'views/project.xml',
        'views/abbreviations.xml',
        'views/task_view.xml',
        'views/standard.xml',
        'views/trf.xml',
        'views/maintenance_checksheet.xml',
        'views/equipment_view.xml',
        'views/parameters.xml',
        'views/protocol.xml',
        'views/process_type.xml',
        'views/qr_code_view.xml',
    ],
    'demo': [],
    'qweb': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}
